name: monitoring
services:

  grafana:
          #    depends_on:
            #      - prometheus
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"
        reservations:
          cpus: "0.1"
          memory: "128M"
    image: grafana/grafana-enterprise:10.0.8
    container_name: grafana
    user: '0'
    networks:
      - default
    ports:
      - "5.44.47.56:3000:3000/tcp"
    restart: always
    volumes:
      - './grafana:/var/lib/grafana'

  prometheus:
# depends_on:
#   - node_exporter
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"
        reservations:
          cpus: "0.1"
          memory: "128M"
    image: prom/prometheus:v2.47.1
    container_name: prometheus
    networks:
      - default
        #    ports:
            #      - "5.44.47.56:9090:9090"
    restart: always
    volumes:
      - 'prometheus:/prometheus'
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=1d'

  node-exporter:
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "32M"
        reservations:
          cpus: "0.1"
          memory: "32M"
    image: prom/node-exporter:v1.6.1
    container_name: node_exporter
    #    network_mode: host
    networks:
      - default
    restart: always
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/:/rootfs:ro'
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  process-exporter:
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "32M"
        reservations:
          cpus: "0.1"
          memory: "32M"
    image: ncabatoff/process-exporter
    container_name: process-exporter
    #    network_mode: host
    privileged: true
    networks:
      - default
        #    ports: 
    #      - "9256:9256"
    restart: always
    volumes:
      - '/proc:/host/proc:ro'
      - './process-exporter.yml:/config/process-exporter.yml'
    command:
      - '--procfs'
      - '/host/proc'
      - '-config.path'
      - '/config/process-exporter.yml'

volumes:
  prometheus: {}
